CREATE TABLE travel_user (
    id SERIAL PRIMARY KEY,
    username VARCHAR(150) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE location (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    image1 TEXT NOT NULL,	
    image2 TEXT NOT NULL,	
    image3 TEXT NOT NULL,	
    description TEXT NOT NULL
);

CREATE TABLE attraction (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    image1 TEXT NOT NULL,	
    image2 TEXT NOT NULL,	
    description TEXT NOT NULL,
    location_id INTEGER REFERENCES location(id) NOT NULL,
    duration_hours INTEGER NOT NULL,
    price FLOAT NOT NULL
);

CREATE TABLE user_itinerary (
    id SERIAL PRIMARY KEY,
    day_num INTEGER NOT NULL,
    user_id INTEGER REFERENCES travel_user(id) NOT NULL,
    attraction_id INTEGER REFERENCES attraction(id) NOT NULL
);


INSERT INTO location			
    (name, image1, image2, image3, description)			
VALUES			
('New York','https://cdn.pixabay.com/photo/2015/03/11/12/31/buildings-668616_960_720.jpg','https://cdn.pixabay.com/photo/2014/02/17/10/20/statue-of-liberty-267948_960_720.jpg','https://cdn.pixabay.com/photo/2016/11/02/10/04/brooklyn-bridge-1791001_960_720.jpg','With a globally recognizable skyline and 8.4 million people who call it home, New York City is bursting with diversity and excitement – from the iconic attractions you have seen on TV and in the movies to hidden gems waiting to be uncovered. Each of the five boroughs – The Bronx, Brooklyn, Manhattan, Queens and Staten Island – has a distinctive flavor, while individual neighborhoods maintain identities all their own. Walkable streets and access to the subway, buses and cabs make it easy to get from neighborhood to neighborhood. Whether it is your first visit or your hundredth, there is always something new to do.'),			
('Tokyo','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/ec/07/79/shibuya-center-town.jpg?w=700&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/62/e7/ea/caption.jpg?w=800&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/d4/fb/caption.jpg?w=1200&h=-1&s=1','With its futuristic skyscrapers, unrivaled food scene, and wild nightlife, Tokyo is a rush of pure adrenaline. This vast and multifaceted city is famously cutting edge, yet its ancient Buddhist temples, vintage teahouses, and peaceful gardens offer a serene escape — and a poignant reminder of the city is long history. And for those who know where to look, Tokyo is smaller pleasures (secret ramen spots, shopping alleys, chill record bars) are often hiding in plain sight.'),			
('Sydney','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/c1/a6/26/caption.jpg?w=1200&h=-1&s=1&cx=2386&cy=2469&chk=v1_f155717087aaeb85b454','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/9f/c9/0c/photo5jpg.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/fc/43/62/sydney-harbour-bridge.jpg?w=1200&h=-1&s=1','Sydney offers an urban mix of rich history and contemporary buzz, but with a distinctly Australian spirit. To understand why this city is so singular, take the clifftop coastal walk from Bondi to Coogee, where you will pass by beaches, rock pools, and lush parks. Then there is the marvelous Sydney Opera House—jutting up like a great origami sailboat—anchoring the city is iconic harbor. It is also worth seeing the city from the top down; the views from the Sydney Tower Eye observatory are epic—and it will get you oriented on how everything is connected.'),			
('Paris','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/15/6d/d6/paris.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/ba/08/3b/photo0jpg.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/c9/29/d4/jardines-de-luxemburgo.jpg?w=1200&h=-1&s=1','Nowhere else on earth makes the heart swoon like the mention of Paris. The city lures with its magnificent art, architecture, culture, and cuisine, but there is also a quieter magic waiting to be explored: the quaint cobbled lanes, the sweet patisseries around the corner, and the cozy little bistros that beckon with a glass of Beaujolais. Get ready to make Paris your own.')
;			


INSERT INTO attraction			
    (name, image1, image2, description, location_id, duration_hours, price)			
VALUES			
('Statue of Liberty & Ellis Island Tour','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/72/13/b5.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/9b/76/3f.jpg','Visits to the Statue of Liberty National Monument and Ellis Island are musts in the Big Apple. On this guided tour, you get boarding on the ferry from Manhattan to visit the two important historical sites. Visit the grounds of Liberty Island and go inside the Statue of Liberty Museum. Then hop the ferry to Ellis Island and learn about the millions of people who arrived here between 1892 and 1954 in hope of living the American dream.',1,3,44),			
('Central Park Walking Tour','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/3b/c3/d1.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/3b/c3/24.jpg','Your guide, Michael Hunt, is not only Central Park is number one tour guide, but also a passionate student of these 843 acres. From its history, wildlife, trees, and plants, statues and structures, he has immersed himself in all that makes the park a living work of art. ',1,3,25),			
('Metropolitan Museum of Art','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/fc/d6/79.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0c/01/f2/e9.jpg','Сlassical antiquity and ancient Egypt, paintings and sculptures from nearly all the European masters, and an extensive collection of American and modern art. This is all about Metropolitan Museum of Art, the largest museum in the United States.',1,4,40),			
('High Line and Chelsea Small Group Tour','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/29/86/0e.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/0a/9e/c1.jpg','Discover the Chelsea neighborhood and it is decorative corners on a walking tour along the High Line. The excursion is perfect for visitors who’ve already seen the typical tourist attractions and want to dig deeper into contemporary New York. Follow your guide along an elevated rail line, then descend into the ultra trendy neighborhood. Explore the Meatpacking District, while your guide provides exciting narration on the area is history and present culture.',1,2,35),			
('New York Premier Dinner Cruise','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/3b/33/a8.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/1a/98/0e.jpg','Escape the crowds and get a different view of the city lights on a dinner cruise along New York is Hudson River. The cruise offers views of city highlights such as the city skyline and Statue of Liberty that you can only get on the water. The cruise also provides the opportunity to indulge in a three-course meal, live entertainment, and dancing.',1,1,200),			
('Tokyo Tower','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/2a/41/27/photo0jpg.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/25/fb/8b/photo0jpg.jpg?w=1200&h=-1&s=1','Odaiba is an entertainment hotspot with a giant ferris wheel, concert halls, amusement arcades and lots of shopping. It also boasts Oedo-onsen-monogatari, a hotspring that recreates old Edo-era ambiance and is very popular with foreign visitors. Shiodome has ultra-modern office buildings where you can often find restaurants with a great high-rise view of Tokyo. The neighboring area of Shinbashi is a district of much older commercial buildings and it is a great place to join salary men enjoying a drink and snacks at street stalls under the railway bridges after work.',2,2,20),			
('Edo-Tokyo Museum','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/df/ac/d1/caption.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/d9/ac/af/photo1jpg.jpg?w=1200&h=-1&s=1','The Tokyo Metropolitan Edo-Tokyo Museum opened its doors in March 1993 as a space to reflect on the history and culture of Edo-Tokyo and envision the city and life of the future. Housed in a unique building modeled after an elevated-floor type warehouse, the museum has been a landmark and popular tourist attraction in Tokyo since its opening. ',2,4,50),			
('Tokyo Metropolitan Government Buildings','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/63/be/41/tokyo-metropolitan-government.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/63/be/af/tokyo-metropolitan-government.jpg?w=1200&h=-1&s=1','The tallest building in Shinjuku, TMG No. 1 offers sweeping views of Tokyo -- all the way to Mt. Fuji on a clear day -- from the 45th floor observatory.',2,1,35),			
('Tokyo DisneySea','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/05/f9/9d/tokyo-disneysea.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/02/ea/e0/magic-hour-tokyo-disneysea.jpg?w=1200&h=-1&s=1','Welcome to Tokyo DisneySea, where imagination and adventure set sail! This is the world is one-and-only Disney theme park themed to the sea. In just 15 minutes by train from Tokyo Station, you will find yourself transported into a completely different realm, featuring diverse attractions filled with a sense of adventure, discovery, and wonder. You can also enjoy entertainment that will captivate your imagination, and delight in relaxing meals paired with alcoholic beverages. This is one of the world is largest theme park that will bring joy to everyone, both children and adults alike.',2,5,70),			
('Tsukiji Outer market tour and cooking class','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/02/dd/8f.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/02/db/66.jpg','We use only the freshest ingredients straight from Tsukiji market.and a varaiety of different food including gluten-free, vegetarian and vegan fare.',2,3,100),			
('Twilight at Taronga','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/2c/d9/20/twilight-at-taronga.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/19/29/57/20180219-193144-largejpg.jpg?w=1200&h=-1&s=1','With a variety of outdoor attractions, the sophisticated harbor suburb of Mosman has something for everyone. Shoppers can stroll Military Road for its unique offering of antiques, designer labels, and hip restaurants and cafes. Nature lovers can take in spectacular bushwalks like the Taronga to Balmoral walk, while families can enjoy snorkeling in the sheltered beaches of Balmoral Beach or scuba diving at Chowder Bay. History lovers enjoy exploring the fortifications at the end of Old Fort Road in Middle Head, which date back to the 1800s. Even the exhibitionist set can find entertainment in Mosman, with several nude beaches located in the area.',3,6,45),			
('Airlie Beach Lagoon','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/8c/ca/a8/photo0jpg.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/ef/52/3d/photo3jpg.jpg?w=1200&h=-1&s=1','Beautiful lagoon Well maintained Life guards very friendly Great atmosphere Great asset to Airlie Beach',3,5,150),			
('Great Barrier Reef Snorkeling and Diving Cruise from Cairns','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/ff/0a/2d.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/71/d7/26.jpg','If snorkeling on the Great Barrier Reef is on your bucket list, do not miss this day trip from Cairns. The 35-metre superyacht, Evolution, departs Cairns with a record 5 hours spent exploring 2 spectacular and exclusive outer Great Barrier Reef locations for an adventure-filled day! You will visit 2 different locations on the barrier reef for the chance to see tropical marine life in the clear waters. Lunch is included onboard the boat, and you have the option to upgrade to include additional adventures such as introductory or certified scuba diving or a helicopter flight over this UNESCO World Heritage site. Both water sports enthusiasts and novices are welcome. Includes instruction and equipment provided by friendly and professional instructors.',3,7,141),			
('Mornington Peninsula National Park','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/bf/13/c3/walking-at-mornington.jpg?w=1200&h=-1&s=1','https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/bf/13/bd/surfing-at-mornington.jpg?w=1200&h=-1&s=1','Mornington Peninsula National Park is a favourite of Melburnians looking to escape the nearby city. Experienced surfers flock to Gunamatta Beach, while rockpools at Sorrento Ocean Beach, close to town, are perfect for families. Dip into the excellent surf beaches of the Mornington Peninsula National Park. Tackle the waves of Gunnamatta, Flinders, Portsea and Rye ocean beaches. Step out on The Coastal Walk for spectacular coastal views. The two-day walk meanders along high clifftops, through coastal vegetation and past stunning ocean beaches. A haven for native wildlife such as kangaroos, Greens Bush is the largest fragment of native bushland remaining on the Mornington Peninsula.',3,6,100),			
('Litchfield National Park and Jumping Crocodile Cruise','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/74/c2/f5.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/74/c2/e7.jpg','Beat other boats to the jumping crocodiles on this early morning adventure. Marvel as saltwater crocs, which can grow up to 17 feet (5 meters), leap from the water to catch meat your guide dangles from the boat. Then explore Litchfield National Park. See termite mounds and swim in three croc-free zones—Wangi Falls, Buley Rockhole, and Florence Falls. Tour includes lunch, snacks, water, and transfers from many Darwin locations.',3,5,131),			
('Versailles Palace Guided Tour with Gardens & Fountains Show from Paris','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/24/fb/f4.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/89/80/ce.jpg','See how the French royalty once lived, and learn all about French history, on this comprehensive four-hour tour of the Palace of Versailles. Getting to the palace, outside central Paris, is easy as you are transported in a private coach. See highlights like the Hall of Mirrors, the Royal Apartments, and the expansive gardens. Enjoy some free time to wander as you please, and even watch a musical fountain display if you are there at the right time.',4,3,100),			
('Big Bus Paris Hop-On Hop-Off Tour','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/79/35/4a.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/7f/a1/e7.jpg','See more of Paris via an open-top, double-decker bus and put aside worries about navigating the streets or using public transportation. This bus tour makes it easy to hop on and off near main Paris attractions, plus hear audio commentary on the city is history, monuments, and museums, available in 11 languages. Plan your own itinerary with 1- or 2-day options and move at the pace you set.',4,4,40),			
('Mont Saint Michel Full Day Experience from Paris by Private Coach','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/06/71/2f/61.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/ed/e0/ce.jpg','Head to the coast of Normandy to visit the picturesque island of Mont-Saint-Michel on this day tour from Paris. You will receive an orientation from your expert guide, and then enjoy free time to explore the UNESCO World Heritage site independently, visit the Mont Saint Michel is Abbey on an audio-guided tour (admission ticket is included), or wander the hilly streets at your leisure. Transportation is by private air-conditioned coach from Paris.',4,3,70),			
('Normandy D-Day Landing Beaches Day Trip with Cider Tasting & Lunch from Paris','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/1a/79/12.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/1a/78/d1.jpg','Set off from central Paris to Normandy on a day trip in honor of D-Day. Military history buffs will find much to admire on this tour of significant World War II sites. Visit a Utah Beach Museum and the American Cemetery, and view Omaha Beach, where Allied forces made their famous Normandy landings.',4,4,80),			
('Versailles - Skip-the-line Private tour from Paris','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/06/f2/a9/43.jpg','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/06/f0/32/21.jpg','If you only visit one French chateau while in Paris, make it the magnificent Palace of Versailles. This private tour lets you explore at your own pace and customise your trip, with skip-the-line entrance and a guided tour including the State Apartments, the Hall of Mirrors, the Apartments of Mesdames, and the palace gardens. ',4,4,80)		
;
